package org.example.appgedbackend.enums;

public enum Category {
    // Avant-projet
    NOTE_CONCEPTUELLE,
    ETUDE_FAISABILITE,
    DIAGNOSTIC_INITIAL,
    AVANT_PROJET_SOMMAIRE,
    ETUDE_IMPACT_ENVIRONNEMENTAL,
    CARTOGRAPHIE_INITIALE,
    CONSULTATION_PARTIES_PRENANTES,
    VALIDATION_BAILLEURS,

    // Pendant projet
    ETUDES_TECHNIQUES_DETAILLEES,
    DOSSIER_APPEL_OFFRES,
    CONTRATS_SPECIFICATIONS,
    PLANNING_PREVISIONNEL,
    RAPPORTS_AVANCEMENT,
    COMPTES_RENDUS_REUNIONS,
    PLAN_ACTION_MISE_OEUVRE,
    ATLAS_CARTOGRAPHIQUE,
    RAPPORTS_INTERMEDIAIRES,

    // Après projet
    RAPPORT_FINAL_EXECUTION,
    EVALUATION_FINALE_IMPACT,
    RECEPTION_OUVRAGES,
    GUIDE_EXPLOITATION_MAINTENANCE,
    PLAN_GESTION_PERNENISATION,
    CAPITALISATION_RETOUR_EXPERIENCE,
    TRANSFERT_AUTORITES
}